#!/bin/bash

mkdir -p anim
for povScript in ./pov/${1}*.pov
do
  povName=`basename $povScript`
  pictName=./anim/${povName%.pov}.png
  
  echo "x-povray +I${povScript} +O${pictName} +W800 +H600 +FN -D"
  x-povray +I${povScript} +O${pictName} +W800 +H600 +FN -D

done
